### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher-docs#2]
Docs should be separated in:
- GUIDE
- API
- TUTORIALS
- SAMPLES

For "Links" "Query" "Exposure"

**Comment by matteodem** [comment]
I'm really interested in getting to know what grapher has to offer. A typical **Getting started** guide would be greatly appreciated.

**Comment by theodorDiaconu** [comment]
Hi @matteodem thanks for your reply. Currently First 2 are off the list. A getting started guide... I believe the best way to do this is by a video tutorial, currently I am focused on bringing the first draft of "Meteor Basics" tutorial, to get the hype on Meteor going again, because I believe people turned away from Meteor 1.5 year ago, but now it's fully packed with enterprise-level features.

https://forums.meteor.com/t/meteor-tutorials-the-plan-we-need-you/30431

After I finish the first chapter. I will focus on Grapher tutorials. Cheers!

**Comment by matteodem** [comment]
cool, definitely looking forward!
